npi.practicaandroid.tutorialnpi.AdaptadorBD Class Reference
This class contains all the methods needed by our application to access the database.
Public Member Functions
AdaptadorBD (Context ctx)
Constructor Initialise the context and the Manager.
AdaptadorBD open () throws SQLException
Open the database.
void close ()
Close the database.
long addContact (String name, String email)
Add a new contact to our database.
boolean removeContactByName (String name)
Remove a contact.
Cursor getAllNames ()
Find all name of the contacts.
Cursor obtenerTodosLosContactos ()
Get all the contacts with their emails.
Cursor obtenerContacto (long idFila) throws SQLException
Get a contact by its ID.
Cursor getEmailByName (String name)
Get the email of a contact given its name.
Static Public Attributes
static final String KEY_IDFILA = `_id`
static final String KEY_NOMBRE = `nombre`
static final String KEY_EMAIL = `email`
Private Attributes
final Context context
DatabaseHelper DBHelper
SQLiteDatabase db
Static Private Attributes
static final String TABLA_BASEDATOS = `contactos`
Detailed Description
This class contains all the methods needed by our application to access the database.
Author
Ruben Bermudez
Santiago Tapia
Isaac Morely
See Also
DatabaseHelper
android.database.sqlite.SQLiteDatabase
Definition at line 43 of file AdaptadorBD.java.
Constructor & Destructor Documentation
npi.practicaandroid.tutorialnpi.AdaptadorBD.AdaptadorBD (Context ctx)
Constructor Initialise the context and the Manager.
Definition at line 56 of file AdaptadorBD.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.context, and npi.practicaandroid.tutorialnpi.AdaptadorBD.DBHelper.
                                   {
        this.context = ctx;
        DBHelper = new DatabaseHelper(context);
    }
Member Function Documentation
long npi.practicaandroid.tutorialnpi.AdaptadorBD.addContact (String name, String email)
Add a new contact to our database.
Parameters
name Name of the contact
email Email of the contact
Returns
ID of the new registry created when adding
Definition at line 84 of file AdaptadorBD.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.db, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_EMAIL, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_NOMBRE, and npi.practicaandroid.tutorialnpi.AdaptadorBD.TABLA_BASEDATOS.
Referenced by npi.practicaandroid.tutorialnpi.AddContact.onCreate().
                                                      {
        ContentValues initialValues = new ContentValues();
        initialValues.put(KEY_NOMBRE, name);
        initialValues.put(KEY_EMAIL, email);
        return db.insert(TABLA_BASEDATOS, null, initialValues)
      ;
    }
void npi.practicaandroid.tutorialnpi.AdaptadorBD.close ()
Close the database.
Definition at line 74 of file AdaptadorBD.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.DBHelper.
Referenced by npi.practicaandroid.tutorialnpi.AddContact.checkConstraints(), npi.practicaandroid.tutorialnpi.AddContact.onCreate(), npi.practicaandroid.tutorialnpi.ReadContact.onCreate(), npi.practicaandroid.tutorialnpi.RemoveContact.onCreate(), npi.practicaandroid.tutorialnpi.ReadContact.onPause(), npi.practicaandroid.tutorialnpi.RemoveContact.onPause(), and npi.practicaandroid.tutorialnpi.AddContact.onPause().
                       {
        DBHelper.close();
    }
Cursor npi.practicaandroid.tutorialnpi.AdaptadorBD.getAllNames ()
Find all name of the contacts.
Returns
Cursor for the list of names retrieved from the database
See Also
android.database.Cursor
Definition at line 105 of file AdaptadorBD.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.db, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_NOMBRE, and npi.practicaandroid.tutorialnpi.AdaptadorBD.TABLA_BASEDATOS.
Referenced by npi.practicaandroid.tutorialnpi.AddContact.checkConstraints(), npi.practicaandroid.tutorialnpi.ReadContact.onCreate(), and npi.practicaandroid.tutorialnpi.RemoveContact.onCreate().
                               {
        String query = "SELECT " + KEY_NOMBRE + " FROM " +
      TABLA_BASEDATOS;
        Log.e("MyDataBase", query);
        Cursor mCursor = db.rawQuery(query, null);
        if (mCursor != null)
            mCursor.moveToFirst();
        return mCursor;
    }
Cursor npi.practicaandroid.tutorialnpi.AdaptadorBD.getEmailByName (String name)
Get the email of a contact given its name.
Parameters
name Name of the contact
Returns
Cursor for this email
See Also
android.database.Cursor
Definition at line 144 of file AdaptadorBD.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.db, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_EMAIL, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_NOMBRE, and npi.practicaandroid.tutorialnpi.AdaptadorBD.TABLA_BASEDATOS.
Referenced by npi.practicaandroid.tutorialnpi.ReadContact.onCreate().
                                              {
        Cursor mCursor = db.query(TABLA_BASEDATOS, new String[
      ] { KEY_EMAIL }, KEY_NOMBRE + "=?", new String[] { String.
      valueOf(name) }, null, null, null, null);
        if (mCursor != null)
            mCursor.moveToFirst();
        return mCursor;
        
    }
Cursor npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerContacto (long idFila) throws SQLException
Get a contact by its ID.
Parameters
idFila ID of the contact
Returns
Cursor for this contact
Exceptions
SQLException If the contact could not be found
See Also
android.database.Cursor
Definition at line 130 of file AdaptadorBD.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.db, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_EMAIL, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_IDFILA, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_NOMBRE, and npi.practicaandroid.tutorialnpi.AdaptadorBD.TABLA_BASEDATOS.
                                                                   {
        Cursor mCursor = db.query(true, TABLA_BASEDATOS, new
      String[] {KEY_IDFILA, KEY_NOMBRE, KEY_EMAIL},
      KEY_IDFILA + "=" + idFila, null, null, null, null, null);
        if (mCursor != null)
            mCursor.moveToFirst();
        
        return mCursor;
    }
Cursor npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerTodosLosContactos ()
Get all the contacts with their emails.
Returns
Cursor for the list of contacts.
See Also
android.database.Cursor
Definition at line 119 of file AdaptadorBD.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.db, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_EMAIL, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_IDFILA, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_NOMBRE, and npi.practicaandroid.tutorialnpi.AdaptadorBD.TABLA_BASEDATOS.
                                            {
        return db.query(TABLA_BASEDATOS, new String[] {
      KEY_IDFILA, KEY_NOMBRE, KEY_EMAIL}, null, null,
      null, null, null);
    }
AdaptadorBD npi.practicaandroid.tutorialnpi.AdaptadorBD.open () throws SQLException
Open the database.
Returns
Itself to allow other calls to method after open the db
Exceptions
SQLException If any problem oppening the db
Definition at line 66 of file AdaptadorBD.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.db, and npi.practicaandroid.tutorialnpi.AdaptadorBD.DBHelper.
Referenced by npi.practicaandroid.tutorialnpi.AddContact.checkConstraints(), npi.practicaandroid.tutorialnpi.AddContact.onCreate(), npi.practicaandroid.tutorialnpi.ReadContact.onCreate(), and npi.practicaandroid.tutorialnpi.RemoveContact.onCreate().
                                                  {
        db = DBHelper.getWritableDatabase();
        return this;
    }
boolean npi.practicaandroid.tutorialnpi.AdaptadorBD.removeContactByName (String name)
Remove a contact.
Parameters
name Name of the contact to remove
Returns
True if the contact have been removed
Definition at line 96 of file AdaptadorBD.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.db, npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_NOMBRE, and npi.practicaandroid.tutorialnpi.AdaptadorBD.TABLA_BASEDATOS.
Referenced by npi.practicaandroid.tutorialnpi.RemoveContact.onCreate().
                                                   {
        return db.delete(TABLA_BASEDATOS, KEY_NOMBRE
       + " = ?", new String[] { String.valueOf(name)}) > 0;
    }
Member Data Documentation
final Context npi.practicaandroid.tutorialnpi.AdaptadorBD.context [private]
Definition at line 48 of file AdaptadorBD.java.
Referenced by npi.practicaandroid.tutorialnpi.AdaptadorBD.AdaptadorBD().
SQLiteDatabase npi.practicaandroid.tutorialnpi.AdaptadorBD.db [private]
Definition at line 50 of file AdaptadorBD.java.
Referenced by npi.practicaandroid.tutorialnpi.AdaptadorBD.addContact(), npi.practicaandroid.tutorialnpi.AdaptadorBD.getAllNames(), npi.practicaandroid.tutorialnpi.AdaptadorBD.getEmailByName(), npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerContacto(), npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerTodosLosContactos(), npi.practicaandroid.tutorialnpi.AdaptadorBD.open(), and npi.practicaandroid.tutorialnpi.AdaptadorBD.removeContactByName().
DatabaseHelper npi.practicaandroid.tutorialnpi.AdaptadorBD.DBHelper [private]
Definition at line 49 of file AdaptadorBD.java.
Referenced by npi.practicaandroid.tutorialnpi.AdaptadorBD.AdaptadorBD(), npi.practicaandroid.tutorialnpi.AdaptadorBD.close(), and npi.practicaandroid.tutorialnpi.AdaptadorBD.open().
final String npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_EMAIL = `email` [static]
Definition at line 46 of file AdaptadorBD.java.
Referenced by npi.practicaandroid.tutorialnpi.AdaptadorBD.addContact(), npi.practicaandroid.tutorialnpi.AdaptadorBD.getEmailByName(), npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerContacto(), and npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerTodosLosContactos().
final String npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_IDFILA = `_id` [static]
Definition at line 44 of file AdaptadorBD.java.
Referenced by npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerContacto(), and npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerTodosLosContactos().
final String npi.practicaandroid.tutorialnpi.AdaptadorBD.KEY_NOMBRE = `nombre` [static]
Definition at line 45 of file AdaptadorBD.java.
Referenced by npi.practicaandroid.tutorialnpi.AdaptadorBD.addContact(), npi.practicaandroid.tutorialnpi.AdaptadorBD.getAllNames(), npi.practicaandroid.tutorialnpi.AdaptadorBD.getEmailByName(), npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerContacto(), npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerTodosLosContactos(), and npi.practicaandroid.tutorialnpi.AdaptadorBD.removeContactByName().
final String npi.practicaandroid.tutorialnpi.AdaptadorBD.TABLA_BASEDATOS = `contactos` [static], [private]
Definition at line 47 of file AdaptadorBD.java.
Referenced by npi.practicaandroid.tutorialnpi.AdaptadorBD.addContact(), npi.practicaandroid.tutorialnpi.AdaptadorBD.getAllNames(), npi.practicaandroid.tutorialnpi.AdaptadorBD.getEmailByName(), npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerContacto(), npi.practicaandroid.tutorialnpi.AdaptadorBD.obtenerTodosLosContactos(), and npi.practicaandroid.tutorialnpi.AdaptadorBD.removeContactByName().
The documentation for this class was generated from the following file:
src/npi/practicaandroid/tutorialnpi/AdaptadorBD.java