npi.practicaandroid.tutorialnpi.ReadContact Class Reference
This class (extended from Activity) allow to read contact from a database.
Protected Member Functions
onCreate
Method called when creating the view
Note
This method initialises the view and set a listener on the spinner. It also show the contact when it is selected on the spinner.
See Also
android.app.Activity::onCreate(android.os.Bundle)
android.widget.EditText
android.widget.Spinner
android.database.Cursor
android.widget.ArrayAdapter
void onCreate (Bundle savedInstanceState)
onPause
This method is called just when the view is not visible for the user (it doesn't mean that the activity is going to be destroyed.
Note
The database is closed to allow other activities to use it
See Also
android.app.Activity::onPause()
void onPause (Bundle savedInstanceState)
Private Attributes
AdaptadorBD dataBase
Spinner names
EditText email
Detailed Description
This class (extended from Activity) allow to read contact from a database.
Author
Ruben Bermudez
Santiago Tapia
Isaac Morely
See Also
android.app.Activity
Definition at line 44 of file ReadContact.java.
Member Function Documentation
void npi.practicaandroid.tutorialnpi.ReadContact.onCreate (Bundle savedInstanceState) [protected]
Definition at line 61 of file ReadContact.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.close(), npi.practicaandroid.tutorialnpi.ReadContact.dataBase, npi.practicaandroid.tutorialnpi.ReadContact.email, npi.practicaandroid.tutorialnpi.AdaptadorBD.getAllNames(), npi.practicaandroid.tutorialnpi.AdaptadorBD.getEmailByName(), npi.practicaandroid.tutorialnpi.ReadContact.names, and npi.practicaandroid.tutorialnpi.AdaptadorBD.open().
                                                       {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_read_contact);
        dataBase = new AdaptadorBD(getBaseContext());
        names = (Spinner) findViewById(R.id.ReadList);
        email = (EditText) findViewById(R.id.ConsultEmail);
        List<String> nameList = new ArrayList<String>();
        try {
            dataBase.open();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        Cursor namesCursor = dataBase.getAllNames();
        dataBase.close();
        if (namesCursor != null){
            while (!namesCursor.isAfterLast()){
                nameList.add(namesCursor.getString(0));
                namesCursor.moveToNext();
            }
        }
        
        ArrayAdapter<String> dataAdapter = new ArrayAdapter<String>(this,
      android.R.layout.simple_spinner_item, nameList);
        dataAdapter.setDropDownViewResource(android.R.layout.
      simple_spinner_dropdown_item);
        names.setAdapter(dataAdapter);
        names.setOnItemSelectedListener(new android.widget.AdapterView.
      OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> arg0, View arg1,
                    int arg2, long arg3) {
                try {
                    dataBase.open();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
                Cursor emails = dataBase.getEmailByName(
      String.valueOf(names.getSelectedItem()));
                dataBase.close();
                email.setText(emails.getString(0));
            }
            @Override
            public void onNothingSelected(AdapterView<?> arg0) {
            }
            
        });
    }
void npi.practicaandroid.tutorialnpi.ReadContact.onPause (Bundle savedInstanceState) [protected]
Definition at line 115 of file ReadContact.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.close(), and npi.practicaandroid.tutorialnpi.ReadContact.dataBase.
                                                      {
        super.onPause();
        dataBase.close();
    }
Member Data Documentation
AdaptadorBD npi.practicaandroid.tutorialnpi.ReadContact.dataBase [private]
Definition at line 45 of file ReadContact.java.
Referenced by npi.practicaandroid.tutorialnpi.ReadContact.onCreate(), and npi.practicaandroid.tutorialnpi.ReadContact.onPause().
EditText npi.practicaandroid.tutorialnpi.ReadContact.email [private]
Definition at line 47 of file ReadContact.java.
Referenced by npi.practicaandroid.tutorialnpi.ReadContact.onCreate().
Spinner npi.practicaandroid.tutorialnpi.ReadContact.names [private]
Definition at line 46 of file ReadContact.java.
Referenced by npi.practicaandroid.tutorialnpi.ReadContact.onCreate().
The documentation for this class was generated from the following file:
src/npi/practicaandroid/tutorialnpi/ReadContact.java