npi.practicaandroid.tutorialnpi.AddContact Class Reference
This class (extended from Activity) allow to add a contact to a database.
Protected Member Functions
onPause
This method is called just when the view is not visible for the user (it doesn't mean that the activity is going to be destroyed.
Note
The database is closed to allow other activities to use it
See Also
android.app.Activity::onPause()
void onPause (Bundle savedInstanceState)
Private Attributes
AdaptadorBD dataBase
onCreate
Method called when creating the view
Note
This method initialises the view and set a click listener on the button. It also add the contact if everything is correct and the button 'save' is pushed. It also inform by toasts when the operation have not been complete or when it is successful.
See Also
android.app.Activity::onCreate(android.os.Bundle)
android.widget.Button;
android.widget.EditText
android.widget.Toast
void onCreate (Bundle savedInstanceState)
int checkConstraints (String name, String email)
Check the constraints to add a new contact.
Detailed Description
This class (extended from Activity) allow to add a contact to a database.
Author
Ruben Bermudez
Santiago Tapia
Isaac Morely
See Also
android.app.Activity
Definition at line 44 of file AddContact.java.
Member Function Documentation
int npi.practicaandroid.tutorialnpi.AddContact.checkConstraints (String name, String email) [private]
Check the constraints to add a new contact.
Parameters
name Name of the contact
email Email of the contact
Returns
0 if everything pass 1 if the contact already exists 2 if name is empty 3 if email is empty
Definition at line 114 of file AddContact.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.close(), npi.practicaandroid.tutorialnpi.AdaptadorBD.getAllNames(), and npi.practicaandroid.tutorialnpi.AdaptadorBD.open().
                                                           {
        try {
            dataBase.open();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        Cursor data = dataBase.getAllNames();
        dataBase.close();
        if (data != null && data.getCount()>0){
            do {
                if (data.getString(0).toLowerCase().equals(name.toLowerCase()))
      {
                    data.close();
                    return 1;
                }
                } while (data.moveToNext());
        }
        if (name.equals(""))
            return 2;
        if (email.equals(""))
            return 3;
        return 0;
    }
void npi.practicaandroid.tutorialnpi.AddContact.onCreate (Bundle savedInstanceState) [protected]
Definition at line 59 of file AddContact.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.addContact(), npi.practicaandroid.tutorialnpi.AdaptadorBD.close(), and npi.practicaandroid.tutorialnpi.AdaptadorBD.open().
                                                       {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add_contact);
        dataBase = new AdaptadorBD(getBaseContext());
        final EditText name = (EditText) findViewById(R.id.AddName);
        final EditText email = (EditText) findViewById(R.id.AddEmail);
        final Button saveButton = (Button) findViewById(R.id.AddSaveButton);
        saveButton.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                String nameToSave = name.getText().toString();
                String emailToSave = email.getText().toString();
                switch(checkConstraints(nameToSave,emailToSave)
      ){
                case 0:
                    try {
                        dataBase.open();
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                    if(dataBase.addContact(nameToSave,
      emailToSave) != -1){
                        dataBase.close();
                        Toast.makeText(AddContact.this,"Contact has been added"
      ,Toast.LENGTH_SHORT).show();
                        AddContact.this.finish();
                    }
                    else {
                        Toast.makeText(AddContact.this,"Contact could not be
       added",Toast.LENGTH_SHORT).show();
                        AddContact.this.finish();
                    }
                    break;
                case 1:
                    Toast.makeText(AddContact.this,"Contact already exists",
      Toast.LENGTH_SHORT).show();
                    break;
                case 2:
                    Toast.makeText(AddContact.this,"Contact name is empty",
      Toast.LENGTH_SHORT).show();
                    break;
                case 3:
                    Toast.makeText(AddContact.this,"Contact email is empty",
      Toast.LENGTH_SHORT).show();
                    break;
                default:
                    break;
                }
            
            }
        });
    }
void npi.practicaandroid.tutorialnpi.AddContact.onPause (Bundle savedInstanceState) [protected]
Definition at line 145 of file AddContact.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.close().
                                                      {
        super.onPause();
        dataBase.close();
    }
Member Data Documentation
AdaptadorBD npi.practicaandroid.tutorialnpi.AddContact.dataBase [private]
Definition at line 45 of file AddContact.java.
The documentation for this class was generated from the following file:
src/npi/practicaandroid/tutorialnpi/AddContact.java