npi.practicaandroid.tutorialnpi.RemoveContact Class Reference
This class (extended from Activity) allow to remove contact from a database.
Protected Member Functions
onCreate
Method called when creating the view
Note
This method initialises the view and set a listener on the button to remove a contact. It remove the contact that is selected on the spinner.
See Also
android.app.Activity::onCreate(android.os.Bundle)
android.widget.EditText
android.widget.Toast
android.widget.Spinner
android.database.Cursor
android.widget.ArrayAdapter
void onCreate (Bundle savedInstanceState)
onPause
This method is called just when the view is not visible for the user (it doesn't mean that the activity is going to be destroyed.
Note
The database is closed to allow other activities to use it
See Also
android.app.Activity::onPause()
void onPause (Bundle savedInstanceState)
Private Attributes
AdaptadorBD dataBase
Button removeButton
Spinner names
Detailed Description
This class (extended from Activity) allow to remove contact from a database.
Author
Ruben Bermudez
Santiago Tapia
Isaac Morely
See Also
android.app.Activity
Definition at line 44 of file RemoveContact.java.
Member Function Documentation
void npi.practicaandroid.tutorialnpi.RemoveContact.onCreate (Bundle savedInstanceState) [protected]
Definition at line 62 of file RemoveContact.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.close(), npi.practicaandroid.tutorialnpi.RemoveContact.dataBase, npi.practicaandroid.tutorialnpi.AdaptadorBD.getAllNames(), npi.practicaandroid.tutorialnpi.RemoveContact.names, npi.practicaandroid.tutorialnpi.AdaptadorBD.open(), npi.practicaandroid.tutorialnpi.RemoveContact.removeButton, and npi.practicaandroid.tutorialnpi.AdaptadorBD.removeContactByName().
                                                       {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_remove_contact);
        dataBase = new AdaptadorBD(getBaseContext());
        removeButton = (Button) findViewById(R.id.RemoveButton);
        names = (Spinner) findViewById(R.id.RemoveList);
        removeButton.setEnabled(false);
        List<String> nameList = new ArrayList<String>();
        try {
            dataBase.open();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        Cursor namesCursor = dataBase.getAllNames();
        dataBase.close();
        if (namesCursor != null){
            if (namesCursor.getCount() > 0)
                removeButton.setEnabled(true);
            while (!namesCursor.isAfterLast()){
                nameList.add(namesCursor.getString(0));
                namesCursor.moveToNext();
            }
        }
        
        ArrayAdapter<String> dataAdapter = new ArrayAdapter<String>(this,
      android.R.layout.simple_spinner_item, nameList);
        dataAdapter.setDropDownViewResource(android.R.layout.
      simple_spinner_dropdown_item);
        names.setAdapter(dataAdapter);
        removeButton.setOnClickListener(new View.OnClickListener()
      {
            public void onClick(View v) {
                String nameToRemove = String.valueOf(names.getSelectedItem
      ());
                try {
                    dataBase.open();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
                boolean result = dataBase.removeContactByName
      (nameToRemove);
                dataBase.close();
                if (result){
                    Toast.makeText(RemoveContact.this,"Contact has been removed
      ",Toast.LENGTH_SHORT).show();
                    RemoveContact.this.finish();
                }
                else {
                    dataBase.close();
                    Toast.makeText(RemoveContact.this,"Error: Contact could not
       be removed",Toast.LENGTH_SHORT).show();
                }
                
            }
        });
    }
void npi.practicaandroid.tutorialnpi.RemoveContact.onPause (Bundle savedInstanceState) [protected]
Definition at line 120 of file RemoveContact.java.
References npi.practicaandroid.tutorialnpi.AdaptadorBD.close(), and npi.practicaandroid.tutorialnpi.RemoveContact.dataBase.
                                                      {
        super.onPause();
        dataBase.close();
    }
Member Data Documentation
AdaptadorBD npi.practicaandroid.tutorialnpi.RemoveContact.dataBase [private]
Definition at line 45 of file RemoveContact.java.
Referenced by npi.practicaandroid.tutorialnpi.RemoveContact.onCreate(), and npi.practicaandroid.tutorialnpi.RemoveContact.onPause().
Spinner npi.practicaandroid.tutorialnpi.RemoveContact.names [private]
Definition at line 47 of file RemoveContact.java.
Referenced by npi.practicaandroid.tutorialnpi.RemoveContact.onCreate().
Button npi.practicaandroid.tutorialnpi.RemoveContact.removeButton [private]
Definition at line 46 of file RemoveContact.java.
Referenced by npi.practicaandroid.tutorialnpi.RemoveContact.onCreate().
The documentation for this class was generated from the following file:
src/npi/practicaandroid/tutorialnpi/RemoveContact.java