npi.practicaandroid.tutorialnpi.DatabaseHelper Class Reference
This class (extended from SQLiteOpenHelper) allows manipulate the database.
Public Member Functions
DatabaseHelper (Context context)
Constructor.
onCreate
Method called when creating the view
Note
It create the database
void onCreate (SQLiteDatabase db)
onUpgrade
Method called when updating the database
Note
The old table is deleted and the database is recreated
See Also
android.database.sqlite.SQLiteOpenHelper::onUpgrade(android.database.sqlite.SQLiteDatabase, int, int)
void onUpgrade (SQLiteDatabase db, int oldVersion, int newVersion)
Static Public Attributes
static final String KEY_IDFILA = `_id`
static final String KEY_NOMBRE = `nombre`
static final String KEY_EMAIL = `email`
Static Private Attributes
static final String NOMBRE_BASEDATOS = `tutorial`
static final int VERSION_BASEDATOS = 1
static final String CREAR_BASEDATOS = `create table contactos (_id integer primary key autoincrement, nombre text not null, email text not null);`
Detailed Description
This class (extended from SQLiteOpenHelper) allows manipulate the database.
Author
Ruben Bermudez
Santiago Tapia
Isaac Morely
See Also
android.database.sqlite.SQLiteOpenHelper;
Definition at line 37 of file DatabaseHelper.java.
Constructor & Destructor Documentation
npi.practicaandroid.tutorialnpi.DatabaseHelper.DatabaseHelper (Context context)
Constructor.
Parameters
context Context of the database
Definition at line 50 of file DatabaseHelper.java.
References npi.practicaandroid.tutorialnpi.DatabaseHelper.NOMBRE_BASEDATOS, and npi.practicaandroid.tutorialnpi.DatabaseHelper.VERSION_BASEDATOS.
                                           {
        super(context, NOMBRE_BASEDATOS, null,
      VERSION_BASEDATOS);
    }
Member Function Documentation
void npi.practicaandroid.tutorialnpi.DatabaseHelper.onCreate (SQLiteDatabase db)
Definition at line 61 of file DatabaseHelper.java.
References npi.practicaandroid.tutorialnpi.DatabaseHelper.CREAR_BASEDATOS.
Referenced by npi.practicaandroid.tutorialnpi.DatabaseHelper.onUpgrade().
                                            {
        db.execSQL(CREAR_BASEDATOS);
    }
void npi.practicaandroid.tutorialnpi.DatabaseHelper.onUpgrade (SQLiteDatabase db, int oldVersion, int newVersion)
Definition at line 73 of file DatabaseHelper.java.
References npi.practicaandroid.tutorialnpi.DatabaseHelper.onCreate().
                                                                             {
        db.execSQL("DROP TABLE IF EXITST contactos");
        onCreate(db);
    }
Member Data Documentation
final String npi.practicaandroid.tutorialnpi.DatabaseHelper.CREAR_BASEDATOS = `create table contactos (_id integer primary key autoincrement, nombre text not null, email text not null);` [static], [private]
Definition at line 44 of file DatabaseHelper.java.
Referenced by npi.practicaandroid.tutorialnpi.DatabaseHelper.onCreate().
final String npi.practicaandroid.tutorialnpi.DatabaseHelper.KEY_EMAIL = `email` [static]
Definition at line 40 of file DatabaseHelper.java.
final String npi.practicaandroid.tutorialnpi.DatabaseHelper.KEY_IDFILA = `_id` [static]
Definition at line 38 of file DatabaseHelper.java.
final String npi.practicaandroid.tutorialnpi.DatabaseHelper.KEY_NOMBRE = `nombre` [static]
Definition at line 39 of file DatabaseHelper.java.
final String npi.practicaandroid.tutorialnpi.DatabaseHelper.NOMBRE_BASEDATOS = `tutorial` [static], [private]
Definition at line 41 of file DatabaseHelper.java.
Referenced by npi.practicaandroid.tutorialnpi.DatabaseHelper.DatabaseHelper().
final int npi.practicaandroid.tutorialnpi.DatabaseHelper.VERSION_BASEDATOS = 1 [static], [private]
Definition at line 43 of file DatabaseHelper.java.
Referenced by npi.practicaandroid.tutorialnpi.DatabaseHelper.DatabaseHelper().
The documentation for this class was generated from the following file:
src/npi/practicaandroid/tutorialnpi/DatabaseHelper.java